#!/usr/bin/env bash

DOTFILES="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

# Kitty
rm -rf $HOME/.config/kitty
ln -sf $DOTFILES/kitty $HOME/.config/kitty

#Tmux
rm -rf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# T script

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

# NVIM
rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim


